### PR TITLE
Python3 compatibility and a file-move-detection bugfix

### PR DESCRIPTION
**Pull request by daytonb**
The code is now Python3 compatible (#116)! It passes the notetests and works as expected with all of the testdata in the repository under Python2 and Python3.

I also fixed a bug with the move detection (#118)

### CODE REVIEW

**Comment by daytonb** [comment]
Is there anything I can do to help with merging this pull request? I'd be happy to help.

**Comment by danvk** [comment]
Thanks @daytonb! Sorry for the slow response. I'll cut a new release.

**Comment by danvk** [comment]
... and it's live! Thanks again! https://pypi.python.org/pypi/webdiff

**Comment by daytonb** [comment]
Awesome! Thanks for accepting my contribution. This tool is really helpful for a project I work on. Especially the image diff capabilities.

**Comment by danvk** [comment]
BTW, would you like to be a maintainer on this project? If the lag time on this PR is any judge, I'm clearly not doing a good job!

**Comment by daytonb** [comment]
Sure. I can try to help maintain it. Is there a direct way to discuss details? I don't know if github provides a way to send messages directly to each other instead of discussing via github issues.

**Comment by danvk** [comment]
You can get my email from my web page (linked to on my GitHub account). I made you a collaborator on the project. If you've got a PyPI account, I'll add you there, too.

Want to try cutting a 0.14 release with #113?

**Comment by daytonb** [comment]
I don't have a PyPI account right now. Since #113 was reported and patched by @NikolasOliveira, and he already has a PyPI account, I think it makes the most sense for him to cut 0.14 rather than me. Are we going to merge the pull request for #109 before 0.14?

**Comment by danvk** [comment]
I wouldn't worry about it for cutting a release. But if one of you could verify that the problem still exists and that the fix doesn't introduce any new errors, that'd be even better.

**Comment by NikolasOliveira** [comment]
@danvk, @daytonb Sure. I'll build a binary gz tonight and test that it installs cleanly and upload it to pypi if so.
@danvk: Is there any tooling (using [twine](https://testpypi.python.org/pypi) or something else) to upload the zipped package? Or do you just do it by hand? Also is there a webdiff package on https://testpypi.python.org/pypi that I can use to stage/test the new binary?

Cheers,
Niko

**Comment by danvk** [comment]
@NikolasOliveira There are some instructions under "To iterate on the PyPI package..." [here][1]. I upload to PyPI with `python setup.py sdist upload`. I make no claims to be competent at Python package distribution. I'm sure there are many ways this process could be improved.

It looks like webdiff [is on test PyPI][2], but I don't usually test things out that way. I just use the tar.gz files. I can add you as a collaborator on the test PyPI if you like.

[1]: https://github.com/danvk/webdiff/blob/95b72375a2703470997fba02ff63946050976d48/README.md#development
[2]: https://testpypi.python.org/pypi/webdiff

**Comment by danvk** [comment]
It would be good to document the process of publishing in a doc (`RELEASING.md`?) or on the GitHub wiki. One step that's easy to forget is updating the version number in both `setup.py` and in `app.py`. Also making sure that dependencies are reflected in both `requirements.txt` and `setup.py`. (Why do we have both? We probably shouldn't!)

**Comment by NikolasOliveira** [comment]
@danvk  If you could add me to the test pypi that'd be great!

Totally agree on the documentation.

For versioning I usually use a standalone module (e.g. version.py) that's imported into the app and setup.py so you only have one place to change the version.

The same can be done for requirements (one requirements.txt file which setup.py reads in and parses, something like [this](https://stackoverflow.com/questions/14399534/reference-requirements-txt-for-the-install-requires-kwarg-in-setuptools-setup-py))

Any who, we should probably move this discussion to a ticket, since it's getting long in the tooth, and this PR isn't the best place for it :p 

I'll whip up a ticket tonight as well.

Cheers,
Niko

**Comment by danvk** [comment]
@NikolasOliveira I added you to the test package.

+1 to everything you said. There's also [`pip install .`][1]

[1]: https://stackoverflow.com/questions/39023758/what-does-pip-install-dot-mean

**Comment by NikolasOliveira** [comment]
@daytonb @danvk just pushed 0.14.0
Passed my local testing and the automated CI build.
Let me know if you see any issues with it otherwise.

Cheers,
Niko

**Comment by daytonb** [comment]
@NikolasOliveira
I tried testing, but I can't seem to get machines other than the host machine to connect to the webpage. I get a message in Chrome which says `This site can't be reached. <hostname> took too long to respond.` I also tried just putting `<host-ipaddress>:<port>` in the non-host computer and got the same message.

I don't know if this is something odd with our network at work.

**Comment by NikolasOliveira** [comment]
@daytonb,

Are you enabling the hostname/diff sharing feature in the config file?
By default webdiff runs in a more secure localhost only mode. Add USE_HOSTNAME=True to your webdiff config file to enable hostname/diff sharing.

If you've done that and you're sure the config is loading properly, then maybe a firewall somewhere in your network?

Let me know how it goes.

Cheers,
Niko

**Comment by daytonb** [comment]
I am use the config file option USE_HOSTNAME=True. I can also tell it's using that because webdiff tells me "Serving diffs on `http://<hostname>:9988` and the local browser that pops open on the host says `<hostname>:9988` in the addressbar rather than `localhost:9988`. I just wanted confirm that it was indeed working for you @NikolasOliveira. If it does then it will probably work for everyone else. Something odd must be set up in my situation. Maybe I'll try again later on a different network.

**Comment by NikolasOliveira** [comment]
Yupp, working for me @daytonb at my office. Was also working on my home network last night.
Let me know what you find with your experimentation on another network.

Cheers,
Niko

**Comment by daytonb** [comment]
Worked for me on another network. Must be something odd about our work network.

**Pull request merged**
